# -*- coding: utf-8 -*-
# Auto-generated crypto kdata schemas will be placed here
# These schemas are generated by gen_kdata_schema function

# This module will contain:
# - CryptoPair{level}Kdata classes (1m, 5m, 15m, 30m, 1h, 4h, 1d)  
# - CryptoPerp{level}Kdata classes (1m, 5m, 15m, 30m, 1h, 4h, 1d)
# - All with bfq adjustment type only (no dividends/splits in crypto)

# Example structure (to be auto-generated):
# from .cryptopair_1m_kdata import CryptoPair1mKdata
# from .cryptopair_5m_kdata import CryptoPair5mKdata 
# from .cryptoperp_1m_kdata import CryptoPerp1mKdata
# etc.

__all__ = []  # Will be populated by schema generator