# -*- coding: utf-8 -*-
# this file is generated by gen_kdata_schema function, don't change it
from sqlalchemy.orm import declarative_base

from zvt.contract.register import register_schema
from zvt.domain.crypto.crypto_kdata_common import CryptoKdataCommon

KdataBase = declarative_base()


class CryptoPerp1mKdata(KdataBase, CryptoKdataCommon):
    __tablename__ = "cryptoperp_1m_kdata"


register_schema(
    providers=["binance", "okx", "bybit", "coinbase", "ccxt"], 
    db_name="cryptoperp_1m_kdata", 
    schema_base=KdataBase, 
    entity_type="cryptoperp"
)


# the __all__ is generated
__all__ = ["CryptoPerp1mKdata"]