# -*- coding: utf-8 -*-
# this file is generated by gen_kdata_schema function, dont't change it
from sqlalchemy.orm import declarative_base

from zvt.contract.register import register_schema
from zvt.domain.quotes import IndexhkKdataCommon

KdataBase = declarative_base()


class Indexhk1dKdata(KdataBase, IndexhkKdataCommon):
    __tablename__ = "indexhk_1d_kdata"


register_schema(providers=["em"], db_name="indexhk_1d_kdata", schema_base=KdataBase, entity_type="indexhk")


# the __all__ is generated
__all__ = ["Indexhk1dKdata"]
