# -*- coding: utf-8 -*-
# this file is generated by gen_kdata_schema function, dont't change it
from zvt.domain.quotes.index.index_1d_kdata import *
from zvt.domain.quotes.index.index_1wk_kdata import *
from zvt.domain.quotes.index.index_1mon_kdata import *