# -*- coding: utf-8 -*-
# this file is generated by gen_kdata_schema function, dont't change it
from sqlalchemy.ext.declarative import declarative_base

from zvt.contract.register import register_schema
from zvt.domain.quotes import IndexKdataCommon

KdataBase = declarative_base()


class Index1monKdata(KdataBase, IndexKdataCommon):
    __tablename__ = 'index_1mon_kdata'


register_schema(providers=['sina','joinquant'], db_name='index_1mon_kdata', schema_base=KdataBase)

__all__ = ['Index1monKdata']
