# -*- coding: utf-8 -*-
# this file is generated by gen_quote_domain function, dont't change it
from zvt.domain.quotes.block.block_1d_kdata import *
from zvt.domain.quotes.block.block_1wk_kdata import *
from zvt.domain.quotes.block.block_1mon_kdata import *