# -*- coding: utf-8 -*-
# this file is generated by gen_kdata_schema function, dont't change it
from sqlalchemy.ext.declarative import declarative_base

from zvt.contract.register import register_schema
from zvt.domain.quotes import FundNetValueCommon

KdataBase = declarative_base()


class FundNetValue(KdataBase, FundNetValueCommon):
    __tablename__ = 'Fund_net_value'


register_schema(providers=['joinquant'], db_name='fund_net_value', schema_base=KdataBase)

__all__ = ['FundNetValue']
