POST http://127.0.0.1:8090/api/work/build_main_tag_industry_relation
accept: application/json
Content-Type: application/json

{
  "main_tag": "AI",
  "industry_list": [
    "互联网服务",
    "软件开发",
    "计算机设备"
  ],
  "activate": true
}