# -*- coding: utf-8 -*-
# this file is generated by gen_kdata_schema function, dont't change it
from zvt.domain.quotes.etf.etf_1d_kdata import *
from zvt.domain.quotes.etf.etf_1d_bfq_kdata import *
from zvt.domain.quotes.etf.etf_1d_hfq_kdata import *