# -*- coding: utf-8 -*-
# this file is generated by gen_kdata_schema function, dont't change it
from sqlalchemy.ext.declarative import declarative_base

from zvt.contract.register import register_schema
from zvt.domain.quotes import BondKdata,KdataCommon

KdataBase = declarative_base()


class Bond1dKdata(KdataBase, BondKdata):
    __tablename__ = 'bond_1d_kdata'


register_schema(providers=['emquantapi'], db_name='bond_1d_kdata', schema_base=KdataBase)

__all__ = ['Bond1dKdata']
