# -*- coding: utf-8 -*-
# this file is generated by gen_kdata_schema function, dont't change it
from zvt.domain.quotes.stock.stock_1m_kdata import *
from zvt.domain.quotes.stock.stock_1m_hfq_kdata import *
from zvt.domain.quotes.stock.stock_5m_kdata import *
from zvt.domain.quotes.stock.stock_5m_hfq_kdata import *
from zvt.domain.quotes.stock.stock_15m_kdata import *
from zvt.domain.quotes.stock.stock_15m_hfq_kdata import *
from zvt.domain.quotes.stock.stock_30m_kdata import *
from zvt.domain.quotes.stock.stock_30m_hfq_kdata import *
from zvt.domain.quotes.stock.stock_1h_kdata import *
from zvt.domain.quotes.stock.stock_1h_hfq_kdata import *
from zvt.domain.quotes.stock.stock_4h_kdata import *
from zvt.domain.quotes.stock.stock_4h_hfq_kdata import *
from zvt.domain.quotes.stock.stock_1d_kdata import *
from zvt.domain.quotes.stock.stock_1d_hfq_kdata import *
from zvt.domain.quotes.stock.stock_1wk_kdata import *
from zvt.domain.quotes.stock.stock_1wk_hfq_kdata import *
from zvt.domain.quotes.stock.stock_1mon_kdata import *
from zvt.domain.quotes.stock.stock_1mon_hfq_kdata import *