# -*- coding: utf-8 -*-
# this file is generated by gen_quote_domain function, dont't change it
from zvt.domain.quotes.stock.stock_1m_kdata import *
from zvt.domain.quotes.stock.stock_5m_kdata import *
from zvt.domain.quotes.stock.stock_15m_kdata import *
from zvt.domain.quotes.stock.stock_30m_kdata import *
from zvt.domain.quotes.stock.stock_1h_kdata import *
from zvt.domain.quotes.stock.stock_4h_kdata import *
from zvt.domain.quotes.stock.stock_1d_kdata import *
from zvt.domain.quotes.stock.stock_1wk_kdata import *
from zvt.domain.quotes.stock.stock_1mon_kdata import *