# -*- coding: utf-8 -*-
# this file is generated by gen_kdata_schema function, dont't change it
from sqlalchemy.ext.declarative import declarative_base

from zvt.contract.register import register_schema
from zvt.domain.quotes import StockQualityFactorCommon

FactorBase = declarative_base()


class StockQualityFactor(FactorBase, StockQualityFactorCommon):
    @classmethod
    def important_cols(cls):
        return ['ACCA', 'accounts_payable_turnover_days', 'accounts_payable_turnover_rate',
                'account_receivable_turnover_days', 'account_receivable_turnover_rate',
                'adjusted_profit_to_total_profit', 'admin_expense_rate',
                'asset_turnover_ttm', 'cash_rate_of_sales',
                'cash_to_current_liability', 'cfo_to_ev', 'current_asset_turnover_rate', 'current_ratio',
                'debt_to_asset_ratio', 'debt_to_equity_ratio', 'debt_to_tangible_equity_ratio',
                'DEGM', 'DEGM_8y', 'DSRI', 'equity_to_asset_ratio',
                'equity_to_fixed_asset_ratio', 'equity_turnover_rate',
                'financial_expense_rate', 'fixed_assets_turnover_rate',
                'fixed_asset_ratio', 'GMI', 'goods_service_cash_to_operating_revenue_ttm',
                'gross_income_ratio', 'intangible_asset_ratio', 'inventory_turnover_days',
                'inventory_turnover_rate', 'invest_income_associates_to_total_profit', 'long_debt_to_asset_ratio',
                'long_debt_to_working_capital_ratio', 'long_term_debt_to_asset_ratio', 'LVGI', 'margin_stability',
                'maximum_margin', 'MLEV', 'net_non_operating_income_to_total_profit',
                'net_operate_cash_flow_to_asset', 'net_operate_cash_flow_to_net_debt',
                'net_operate_cash_flow_to_operate_income', 'net_operate_cash_flow_to_total_current_liability',
                'net_operate_cash_flow_to_total_liability', 'net_operating_cash_flow_coverage', 'net_profit_ratio',
                'net_profit_to_total_operate_revenue_ttm', 'non_current_asset_ratio',
                'OperatingCycle', 'operating_cost_to_operating_revenue_ratio',
                'operating_profit_growth_rate', 'operating_profit_ratio', 'operating_profit_to_operating_revenue',
                'operating_profit_to_total_profit', 'operating_tax_to_operating_revenue_ratio_ttm',
                'profit_margin_ttm', 'quick_ratio', 'rnoa_ttm',
                'ROAEBITTTM', 'roa_ttm', 'roa_ttm_8y', 'roe_ttm', 'roe_ttm_8y', 'roic_ttm',
                'sale_expense_to_operating_revenue',
                'SGAI', 'SGI', 'super_quick_ratio', 'total_asset_turnover_rate',
                'total_profit_to_cost_ratio']

    __tablename__ = 'stock_quality_factor'


register_schema(providers=['joinquant'], db_name='stock_quality_factor', schema_base=FactorBase)

__all__ = ['StockQualityFactor']
