# -*- coding: utf-8 -*-
# this file is generated by gen_kdata_schema function, dont't change it
from sqlalchemy.ext.declarative import declarative_base

from zvt.contract.register import register_schema
from zvt.domain.quotes import StockMomentumFactorCommon

FactorBase = declarative_base()


class StockMomentumFactor(FactorBase, StockMomentumFactorCommon):
    @classmethod
    def important_cols(cls):
        return [
            'arron_down_25', 'arron_up_25', 'BBIC', 'bear_power', 'BIAS10', 'BIAS20',
            'BIAS5', 'BIAS60', 'bull_power', 'CCI10', 'CCI15',
            'CCI20', 'CCI88', 'CR20', 'fifty_two_week_close_rank', 'MASS', 'PLRC12', 'PLRC24',
            'PLRC6', 'Price1M', 'Price1Y', 'Price3M', 'Rank1M', 'ROC12', 'ROC120',
            'ROC20', 'ROC6', 'ROC60', 'single_day_VPT',
            'single_day_VPT_12', 'single_day_VPT_6', 'TRIX10',
            'TRIX5', 'Volume1M']

    __tablename__ = 'stock_momentum_factor'


register_schema(providers=['joinquant'], db_name='stock_momentum_factor', schema_base=FactorBase)

__all__ = ['StockMomentumFactor']
