# -*- coding: utf-8 -*-
# this file is generated by gen_kdata_schema function, dont't change it
from sqlalchemy.ext.declarative import declarative_base

from zvt.contract.register import register_schema
from zvt.domain.quotes import StockTechnicalFactorCommon

FactorBase = declarative_base()


class StockTechnicalFactor(FactorBase, StockTechnicalFactorCommon):
    @classmethod
    def important_cols(cls):
        return ['boll_down', 'boll_up', 'EMA5', 'EMAC10', 'EMAC12', 'EMAC120', 'EMAC20', 'EMAC26', 'MAC10',
                'MAC120', 'MAC20', 'MAC5', 'MAC60', 'MACDC', 'MFI14']

    __tablename__ = 'stock_technical_factor'


register_schema(providers=['joinquant'], db_name='stock_technical_factor', schema_base=FactorBase)

__all__ = ['StockTechnicalFactor']
