# -*- coding: utf-8 -*-
# this file is generated by gen_kdata_schema function, dont't change it
from sqlalchemy.ext.declarative import declarative_base

from zvt.contract.register import register_schema
from zvt.domain.quotes import StockEmotionFactorCommon

FactorBase = declarative_base()


class StockEmotionFactor(FactorBase, StockEmotionFactorCommon):
    @classmethod
    def important_cols(cls):
        return ['AR', 'ARBR', 'ATR14', 'ATR6', 'BR', 'DAVOL10', 'DAVOL20',
                'DAVOL5', 'MAWVAD', 'money_flow_20', 'PSY',
                'turnover_volatility', 'TVMA20', 'TVMA6', 'TVSTD20', 'TVSTD6',
                'VDEA', 'VDIFF', 'VEMA10', 'VEMA12', 'VEMA26', 'VEMA5',
                'VMACD', 'VOL10', 'VOL120', 'VOL20', 'VOL240', 'VOL5', 'VOL60', 'VOSC',
                'VR', 'VROC12', 'VROC6', 'VSTD10', 'VSTD20', 'WVAD']

    __tablename__ = 'stock_emotion_factor'


register_schema(providers=['joinquant'], db_name='stock_emotion_factor', schema_base=FactorBase)

__all__ = ['StockEmotionFactor']
